name: Google Cloud Authentication

on:
  push:
    branches:
      - main

jobs:
  authenticate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0.5.0
        with:
          workload_identity_provider: projects/website-444303/locations/global/workloadIdentityPools/github/providers/github-actions-provider
          service_account: website-cloudun@website-444303.iam.gserviceaccount.com

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.6.0

      - name: Run gcloud command
        run: |
          gcloud auth list
          gcloud config set project website-444303
